[package]
name = "game-of-life"
version = "0.1.0"
edition = "2021"

[dependencies]
simple_logger = "4.0.0"
log = "0.4"
wgpu = "0.15"
pollster = "0.2"
bytemuck = { version = "1.12", features = [ "derive" ] }
cgmath = "0.18"
egui = "0.21.0"
egui-winit = "0.21.1"
egui-wgpu = "0.21.0"
